title: "Mental Health Disorders in Latin American University Populat"
description: "Statistical database on the prevalence of mental health disorders, risk factors, and protective variables in Latin American university populations. Co"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/mental-health-disorders-in-latin-american-university-population-prevalence-risk-"
